"""tables merged

Revision ID: 08c1c3a49e02
Revises: cc015bff60cf
Create Date: 2021-10-26 09:16:47.154318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c1c3a49e02'
down_revision = 'cc015bff60cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('identity', sa.String(length=5), nullable=True))
    op.drop_index('ix_log_student', table_name='log')
    op.create_index(op.f('ix_log_identity'), 'log', ['identity'], unique=False)
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['identity'], ['identity'])
    op.drop_column('log', 'student')
    op.add_column('user', sa.Column('identity', sa.String(length=5), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_student_id', table_name='user')
    op.create_index(op.f('ix_user_identity'), 'user', ['identity'], unique=True)
    op.drop_column('user', 'editor')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('editor', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_user_identity'), table_name='user')
    op.create_index('ix_user_student_id', 'user', ['student_id'], unique=False)
    op.drop_column('user', 'admin')
    op.drop_column('user', 'identity')
    op.add_column('log', sa.Column('student', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['student'], ['student_id'])
    op.drop_index(op.f('ix_log_identity'), table_name='log')
    op.create_index('ix_log_student', 'log', ['student'], unique=False)
    op.drop_column('log', 'identity')
    # ### end Alembic commands ###
