"""admin table

Revision ID: 2e38aea7c783
Revises: e694930349a2
Create Date: 2021-10-22 12:53:50.642287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e38aea7c783'
down_revision = 'e694930349a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_code', sa.String(length=3), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_admin_first_name'), 'admin', ['first_name'], unique=False)
    op.create_index(op.f('ix_admin_last_name'), 'admin', ['last_name'], unique=False)
    op.create_index(op.f('ix_admin_teacher_code'), 'admin', ['teacher_code'], unique=False)
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['student'], ['id'])
    op.drop_index('ix_user_student_id', table_name='user')
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.create_index('ix_user_student_id', 'user', ['student_id'], unique=False)
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['student'], ['student_id'])
    op.drop_index(op.f('ix_admin_teacher_code'), table_name='admin')
    op.drop_index(op.f('ix_admin_last_name'), table_name='admin')
    op.drop_index(op.f('ix_admin_first_name'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
