"""empty message

Revision ID: 52ddba18ad33
Revises: 2e38aea7c783
Create Date: 2021-10-22 13:27:10.825598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ddba18ad33'
down_revision = '2e38aea7c783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_code'), 'code', ['code'], unique=True)
    op.drop_index('ix_user_student_id', table_name='user')
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.create_index('ix_user_student_id', 'user', ['student_id'], unique=False)
    op.drop_index(op.f('ix_code_code'), table_name='code')
    op.drop_table('code')
    # ### end Alembic commands ###
