"""editor added

Revision ID: cc015bff60cf
Revises: 52ddba18ad33
Create Date: 2021-10-26 08:24:33.649306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc015bff60cf'
down_revision = '52ddba18ad33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('editor', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('editor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'editor')
    op.drop_column('admin', 'editor')
    # ### end Alembic commands ###
